### PR TITLE
Updates to Opencore (0.7.5) and kexts

### PR DESCRIPTION
**Pull request by 82ghost82**
More and more users are experiencing issues after installing a working copy of mac os through macinabox because they use opencore configurator to easily configure smbios data.
The issue is that opencore changed a little the config.plist structure and newer versions of opencore configurator are not backward compatible.
The standard user downloads the latest version of opencore configurator and doesn't know that ideally each version of opencore requires a specific version of the configurator.
Using the latest version of opencore configurator on an older version of opencore results in an unbootable system.
This update tries to fix this issue even if opencore configurator is not and was never supported by Acidanthera.

Updates
Opencore 0.7.5 debug
AppleALC updated to 1.6.6 debug
Lilu updated to 1.5.7 debug
VirtualSMC updated to 1.2.7 debug
Whatevergreen updated to 1.5.5 debug

### CODE REVIEW

**Comment by SeniorHeld** [comment]
Hi, after finishing the first installation I can't start the VM from disk. I can only start from install media.

**Comment by 82ghost82** [comment]
what is "first installation"?

**Comment by SeniorHeld** [comment]
I mean the initial installation from the installation media on the hard disk. 
When I run macinabox for the first time I have to install macOS.

**Comment by 82ghost82** [comment]
So, you mean that after installation you don't see any boot entries in opencanopy apart the installation medium?

**Comment by SeniorHeld** [comment]
Yes. Exactly.

**Comment by 82ghost82** [comment]
What os did you install?just for confirmation you wrote Mojave, Big Sur, Monterey?

**Comment by SeniorHeld** [comment]
I tried Mojave, Big Sur and Monterey. I have this issue with all of those.

**Comment by 82ghost82** [comment]
I found an issue with the configuration, which was not able to boot any < Big Sur mac os...but Monterey and Big Sur are displayed correctly and boot without any issue.
Can you try this image and apply it to the docker?
https://mega.nz/file/5rYyFZjb#T6Oayj64QRX9r6uiaJp0XMsaUiN6PugOxLHt0OInldc

**Comment by SeniorHeld** [comment]
With your new image it works flawlessly! Thanks for your quick responses!

**Comment by 82ghost82** [comment]
Thank you to you for reporting.
I will close this and open a new one with the new image.

**Pull request closed without merging**
